// eslint-disable-next-line import/prefer-default-export
//USER
export const USER_LOGIN_INITIATE = 'USER_LOGIN_INITIATE';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';
//ADDEXPENSE
export const ADD_EXPENSE_INITIATE = 'ADD_EXPENSES_INITIATE';
export const ADD_EXPENSE_SUCCESS = 'ADD_EXPENSES_SUCCESS';
export const ADD_EXPENSE_ERROR = 'ADD_EXPENSES_ERROR';
//EDITEXPENSE
export const EDIT_EXPENSES_INITIATE ='EDIT_EXPENSES_INITIATE';
export const EDIT_EXPENSES_SUCCESS ='EDIT_EXPENSES_SUCCESS';
export const EDIT_EXPENSES_ERROR ='EDIT_EXPENSES_ERROR';
//LISTEXPENSE
export const EXPENSES_LIST_INITIATE = 'EXPENSES_LIST_INITIATE';
export const EXPENSES_LISTSAGA_SUCCESS = 'EXPENSES_LISTSAGA_INITIATE';
export const EXPENSES_LISTSAGA_ERROR = 'EXPENSES_LISTSAGA_ERROR';
